# Generated by Django 3.2.10 on 2021-12-29 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20211229_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='descrption',
            new_name='description',
        ),
    ]
